function myFunction(a, b) {
    c = a + b
    console.log(c)

}
try {
    myFunctionnnn(1, 2)
}
catch (err) {
    console.log(err)
}
console.log(666)